### ISSUE TITLE
How test?

### ISSUE THREAD

**Issue by andreyddk** [MoonLiightz/CPP-Telegram-Class#1]
It is work? How i acn test?

**Comment by MoonLiightz** [comment]
Yes, it works. Everything you have to know is written in the example.cpp.
More functions comming soon.

**Comment by andreyddk** [comment]
how compile?

**Comment by MoonLiightz** [comment]
Under Unix:

`g++ src/tgapi.cpp example.cpp -o example -lcurl`

Don't forgett to install curl.
